<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE pages [
    <!ELEMENT pages (page*)>

    <!ELEMENT page ANY>
    <!ATTLIST page
        id        ID    #REQUIRED
        type      CDATA #IMPLIED
        arguments CDATA ""
        menu      CDATA #IMPLIED
        alias     CDATA #IMPLIED
    >

    <!ELEMENT list (link*, nest*, list*)>
    <!ATTLIST list
        class  CDATA "links"
        before CDATA #IMPLIED
        after  CDATA #IMPLIED
        type   CDATA #IMPLIED
    >

    <!ELEMENT link EMPTY>
    <!ATTLIST link
        class       CDATA "link"
        id          CDATA ""
        src         CDATA #REQUIRED
        text        CDATA #IMPLIED
        before      CDATA #IMPLIED
        after       CDATA #IMPLIED
        type        CDATA #IMPLIED
        domain      CDATA #IMPLIED
        menu        CDATA #IMPLIED
    >

    <!ELEMENT nest ANY>
    <!ATTLIST nest
        class   CDATA "nest"
        style   CDATA "margin-left: 10px;"
    >
]>

<!--
This XML file can contain the whole website or it can contain just the main pages.

Writing it is really simple, each page can contain CDATA sections or links collections

Page tags also have type and arguments attributes these are defaults for the page,
they can be overloaded by the query.

CDATA sections are outputted as they are.
Links collections are outputted like lists of links.

The example below should be self explanatory.
-->

<pages>
    <page id="home">
        <![CDATA[
            This is a homepage.
        ]]>
    </page>

    <page id="links">
        <![CDATA[
            This is a links collection:<br/>
        ]]>
        <list before="-&#160;">
            <link domain="in" src="stuff" text="Stuff" arguments="decoration=- times=40" after=" ~ Internal link"/>
            <link src="separated" text="Separated" after=" ~ Internal link but in data/"/>
            <link src="#separated" text="Separated" after=" ~ Separated alias'd"/>
            <link src="http://lulz.thruhere.net" text="IN LULZ WE TRUST" after=" ~ External link"/>
        </list>
    </page>

    <page id="separated" alias="#page=separated"/>

    <page id="stuff" menu="stuff" type="simple" arguments="decoration=~ times=20">
        <![CDATA[NIGGER NIGGER NIGGER NIGGER NIGGER NIGGER
             NIGGER NIGGER NIGGER NIGGER NIGGER NIGGER
             NIGGER NIGGER NIGGER NIGGER NIGGER NIGGER
        ]]>
    </page>
</pages>
